rubyforgood/stocks-in-the-future

Gemfile, Gemfile.lock, app/controllers/home_controller.rb, app/models/user.rb, app/views/home/index.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20230729152416_devise_create_users.rb, db/schema.rb, spec/system/users_spec.rb
1. Add devise gem
2. Created user model
3. Add test for sign up flow
=> Add devise

LICENSE.md, code-of-conduct.md
Adds LICENSE & Code of Conduct
=> Add LICENSE & Code of Conduct

README.md, bin/docker-entrypoint, docker-compose.yml
Updating readme with instructions for running within the docker container.
=> Instructions

.github/ISSUE_TEMPLATE.md, .github/pull_request_template.md
Adds an issue template & more verbose PR template
=> Adds issue template & more verbose PR template

Gemfile, Gemfile.lock
I want to help keep the app secure. I am working on the  *initial* ci  which will make use of bundler audit. 
* User information being accessible by unauthorized third parties
* User secrets being visible 
* Package vulnerabilities
* Other security issues....
=> Add bundler audit because security is #1

bin/docker-entrypoint
stop trying to glob the comparison, because it's not being caught, and I'm tired of fighting with bash comparisons...
=> Fix the entrypoint to actually run migrations

.github/workflows/docker-build.yml, app/models/user.rb, db/schema.rb, spec/system/users_spec.rb
Resolves #000 
- Fixes outstanding lint issues
- Temporarily marks a broken test pending 
* Bug fix (non-breaking change which fixes an issue)
=> Fix lint and mark broken test pending for now

Gemfile, Gemfile.lock, app/models/user.rb, db/migrate/20230802134455_add_role_to_users.rb, db/schema.rb, spec/factories/users.rb, spec/models/user_spec.rb, spec/rails_helper.rb
Resolves #28 
- Include summary of change and what issue is fixed, including relevant motivation and context.
- Role enum added to User model (admin, alumni, student, teacher)
- Added user factory to assist with testing
- Explain the need for any added dependencies for this change.
- Added shoulda-matchers gem to assist with testing
- Added pry gem
- How have you tested this?
- `define_enum_for` matcher - last test in user_spec.rb
- Anything else we should know about?
- Unsure how a user will have more than one role (as described in the issue)
* New feature (non-breaking change which adds functionality)
N/A
=> Add role to user

Gemfile, Gemfile.lock, db/schema.rb
Upgrades to Redis 5. 
Also checks in automated changes made to schema.rb. Will need to watch to see if this is flapping back and forth or someone/something made non-automated changes to file.
=> Upgrade redis

app/models/stocks/marketstack_api.rb, app/models/stocks/price.rb
Applies some of the feedback from #32 .
Verified functionality is still working via setting up a free access token for myself at https://marketstack.com/ .
I may loop back to apply more feedback, or create some issues with followup steps.
Things that need to be done:
- Move values into config
- Use Redis cache wrappers, [as mentioned here](https://github.com/rubyforgood/stocks-in-the-future/pull/37#discussion_r1280592493)
- Leverage ActiveModel, [as mentioned here](https://github.com/rubyforgood/stocks-in-the-future/pull/37#discussion_r1280595107)
- Consider using `Faraday` instead of `Net::HTTP`, [as mentioned here](https://github.com/rubyforgood/stocks-in-the-future/pull/32#discussion_r1278585113)
- More refactoring. [Here's one relevant …
=> Initial refactors of Stock logic - Not comprehensive

.gitignore, app/views/devise/shared/_links.html.erb, config/routes.rb, spec/system/users_spec.rb
Resolves #65 
- Removed the sign-up feature from the app
* Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> [65] Remove the registration feature

config/environments/test.rb, spec/system/users_spec.rb
- Added system specs for login and password reset flow
* Added specs
=> Add system specs for login and password reset flow

app/models/admin.rb, app/models/classroom.rb, app/models/company.rb, app/models/portfolio.rb, app/models/portfolio_stock.rb, app/models/portfolio_transaction.rb, app/models/stock.rb, app/models/student.rb, app/models/teacher.rb, db/migrate/20240424040256_create_table_relations.rb, db/migrate/20240424042515_add_stock_to_companies.rb, db/schema.rb, test/fixtures/companies.yml, test/fixtures/portfolio_stocks.yml, test/fixtures/portfolio_transactions.yml, test/fixtures/portfolios.yml, test/fixtures/stocks.yml, test/models/company_test.rb, test/models/portfolio_test.rb, test/models/portfolio_transaction_test.rb, test/models/stock_test.rb
This PR updates the schema to include all new relationships needed to build the portfolio as well as the models for them.
=> Creating tables, relationships, and models

docs/schema.md
This pull request introduces a new schema for the application, as outlined in the `docs/schema.md` file. The schema includes various tables such as `schools`, `years`, `school_years`, `classrooms`, `users`, `user_invites`, `stocks`, `stock_prices`, `stock_dividends`, `portfolio`, `portfolio_transactions`, `portfolio_stocks`, and `portfolio_stock_transactions`. Each table has its own set of fields, and some tables also include a `type` field to differentiate between different types of records, such as different types of users or transactions.
Newly introduced schema:
* [`docs/schema.md`](diffhunk://#diff-79f5d80ee02a931b2bf12fd018b6edeb447abd58e1fb85ae155ae932ec29ad9dR1-R99): Introduced a new schema for the application, including tables for schools, years, school years, classrooms, users, …
=> Added Schema Doc

db/migrate/20240424154028_remove_company_and_add_to_stock.rb, db/schema.rb
removed companies and add company info to stocks
=> Update stock table

app/models/user.rb, db/migrate/20240424162035_remove_unique_index_from_email.rb, db/schema.rb, db/seeds.rb
This allow for many users to not have an email but for all emails to still be uniq
=> Fixing email uniqness when blank

.github/ISSUE_TEMPLATE.md, .github/dependabot.yml, Gemfile, Gemfile.lock, LICENSE.md
This pulls files out of https://github.com/rubyforgood/stocks-in-the-future/pull/132 that are not related to github workflow files
This pulls a few select config files files prior to https://github.com/rubyforgood/stocks-in-the-future/pull/116
=> Restore some old config files

Gemfile, Gemfile.lock, app/models/order.rb, app/models/stock.rb, app/models/user.rb, db/migrate/20240531160059_create_orders.rb, db/migrate/20240531175616_remove_price_info_from_stocks.rb, db/migrate/20240531175716_add_price_to_stocks.rb, db/schema.rb, test/fixtures/orders.yml, test/fixtures/stocks.yml, test/fixtures/users.yml, test/models/order_test.rb
Starts work on #145
Created order model
Fixed some tests and fixtures
Added npm and yarn to docker, separate commit
=> Order resource 145

app/dashboards/student_dashboard.rb, app/dashboards/teacher_dashboard.rb, app/dashboards/user_dashboard.rb
Removed fields encrypted_password, remember_created_at, reset_password_sent_at, and reset_password_token from administrative views. Fixes #141
=> Remove extra fields from administrative views. Fixes #141

app/controllers/admin/students_controller.rb, app/dashboards/portfolio_transaction_dashboard.rb, app/models/portfolio.rb, app/models/student.rb, app/models/user.rb, app/views/admin/students/_form.html.erb, config/environments/test.rb, config/routes.rb, db/migrate/20240531145714_add_amount_to_portfolio_transactions.rb, db/migrate/20240531151002_remove_cash_balance_from_portfolios.rb, db/schema.rb, test/controllers/admin/students_controller_test.rb, test/fixtures/portfolio_transactions.yml, test/fixtures/portfolios.yml, test/fixtures/users.yml, test/fixtures/years.yml, test/models/portfolio_test.rb
Addresses issue #142 
- Add custom student form that displays cash balance and allows add_fund_amount
=> Add student funds to admin

app/controllers/admin/students_controller.rb, app/views/admin/students/_form.html.erb, test/controllers/admin/students_controller_test.rb
- Small changes for #142 we noticed after more testing with tests for the failing cases
=> Fixes for #142

Gemfile, Gemfile.lock, Procfile.dev, bin/delayed_job, config/application.rb, db/migrate/20240601143331_create_delayed_jobs.rb, db/schema.rb
Gems installed:
- daemons
- delayed_job_active_record
Updated Procfile.dev to include running delayed_job
=> Setup delayed_job and basic configuration

db/seeds.rb
Fixed seeding of a test user in the database
=> fixed an issue so test user is created properly

test/fixtures/stocks.yml
Added company_name to stocks test fixture
=> Fixed missing field from test fixture

README.md
=> Added SIF, ruby for good, and repo information

README.md, app/views/components/ui/_checkbox.html.erb
Make the "Remember me" label clickable
Link to the issue:
https://github.com/rubyforgood/stocks-in-the-future/issues/149
=> Make check box label clickable

app/controllers/classrooms_controller.rb, app/views/classrooms/_classroom_students_table.html.erb, app/views/classrooms/show.html.erb
Fix #253 
- Created classroom student table in classroom show page
- Preloaded associations to avoid n+1 queries
=> Fix #253 Render classroom students table in the Classroom view

app/views/layouts/application.html.erb
Resolves #269 
Removes navbar when logged out
=> Remove navbar when logged out

.rubocop_todo.yml, app/dashboards/portfolio_transaction_dashboard.rb, app/helpers/components/button_helper.rb, app/helpers/components/input_helper.rb, test/models/sti_test.rb, test/services/purchase_stock_test.rb
Resolves rubocop line length errors in #296
=> Resolve rubocop line length errors #296

.rubocop_todo.yml, app/controllers/classrooms_controller.rb, app/controllers/orders_controller.rb, app/controllers/schools_controller.rb, app/controllers/students_controller.rb
Resolves RuboCop Strong Parameters errors #296
=> Resolve rubocop strong params errors #296

app/models/portfolio_transaction.rb
=> Add comment on what transaction types mean

app/controllers/students_controller.rb, app/models/student.rb, app/models/user.rb, config/locales/en.yml, db/seeds.rb, test/controllers/application_controller_test.rb, test/controllers/students_controller_test.rb
Make sure there is a portfolio creation for new students
Add `accepts_nested_attributes_for` Portfolio to User model to enable portfolio creation via nested attributes
Add `after_create`callback to Student model to guarantee every student gets a portfolio
Update seeds.rb to give them a portfolio
Remove controller-specific portfolio creation because the logic is now in the  model
Resolves #304
=> Make sure new students get an empty portfolio

app/helpers/application_helper.rb, app/views/layouts/_navbar.html.erb, app/views/layouts/application.html.erb, app/views/stocks/show.html.erb
=> Add new navbar 281

app/models/order.rb, app/models/portfolio.rb, app/models/portfolio_transaction.rb, test/factories/orders.rb, test/factories/portfolio_transactions.rb, test/models/order_test.rb, test/models/portfolio_test.rb, test/models/portfolio_transaction_test.rb
Changes how cash_balance calculates the amount of funds available for purchasing.
=> cash_balance should reflect available balance that can be used to make a purchase fixes #314

app/models/classroom.rb, test/models/classroom_test.rb
https://github.com/rubyforgood/stocks-in-the-future/issues/300
=> Remove destroy dependent

app/assets/stylesheets/custom/buttons.css, app/views/layouts/_navbar.html.erb, app/views/layouts/application.html.erb
Styling updates to get the navbar to get closer to the style the designer chose
=> Styling updates

app/controllers/orders_controller.rb, app/models/portfolio.rb, app/views/orders/_form.html.erb, app/views/orders/edit.html.erb, app/views/orders/new.html.erb, test/factories/portfolio_stocks.rb, test/models/portfolio_test.rb
Resolves https://github.com/rubyforgood/stocks-in-the-future/issues/346
=> 346 Adding shares owned on buy/sell form

app/javascript/controllers/order_form_controller.js, app/views/orders/_form.html.erb
Solves https://github.com/rubyforgood/stocks-in-the-future/issues/347
=> Add total cost as a user buys shares

app/views/classrooms/_form.html.erb
Resolves #265  . 
This fixes an issue where school_name and year values were not pre-filled on the classroom edit form, which caused errors when saving with blank values. The form now correctly displays the current values for school and year.
* Bug fix (non-breaking change which fixes an issue)
No automated tests were added as this is a simple view-only change.
Manual Testing Steps
1. Log in as Admin:
```
Username: Admin
Password: password
```
2. Click the Edit this classroom button to go to the classroom edit page.
Example:
```
http://localhost:3000/classrooms/1/edit
```
3. Confirm that the **School Name** and **Year** fields are pre-filled with the current values.
=> 265 Prefill school name and year on classroom edit form

app/dashboards/classroom_dashboard.rb, app/dashboards/school_year_dashboard.rb
resolves #384 and #385 
Fixed no method error bug
Updated ClassroomDashboard to match the actual model associations
Improved School Year Dropdown
Add Grade Dropdown
=> Fix admin classroom bug

app/controllers/application_controller.rb, app/controllers/classrooms_controller.rb, app/policies/classroom_policy.rb, app/views/classrooms/_classroom.html.erb, test/controllers/application_controller_test.rb, test/controllers/classrooms_controller_test.rb, test/helpers/policy_test_helper.rb, test/policies/classroom_policy_test.rb, test/test_helper.rb
As per the changes that you have requested, I have made the necessary code changes to ensure that the classroom routes are protected as the logic that has been requested.
In addition to that, one important thing I have noticed and added a fix for it as well.
1. Only the teachers who have the classrooms assigned to them are authorized to see their classrooms and not have **show** access to other classrooms. 
a. To ensure this behaviour, I have added an action to the `classrooms_controller`  and have added tests for this feature as well. Let me know if this is the expected behaviour or not.
=> Closes #371

app/services/purchase_stock.rb, test/services/purchase_stock_test.rb
=> Fix purchase stock bug

db/seeds/partials/years.rb, db/seeds/production.rb
It resolves https://github.com/rubyforgood/stocks-in-the-future/issues/441
=> #441 adding more dynamic year seed data + production seed

app/models/order.rb, app/views/portfolios/_stock_card.html.erb, app/views/stocks/_stock.html.erb, app/views/stocks/_stocks_table.html.erb, test/models/order_test.rb
It resolves https://github.com/rubyforgood/stocks-in-the-future/issues/439
=> 439 student cannot buy archived stocks

app/views/portfolios/_earnings_to_invest_card.html.erb, app/views/portfolios/show.html.erb
=> Cleanup table on Portfolio page

db/seeds/partials/orders.rb, db/seeds/partials/portfolio_transactions.rb
Was getting a nil error when running the seeds file when a stock doesnt have a price. Just skipping over those stocks for now
=> Add a nil check that was causing failures

.github/workflows/ci.yml, README.md, app/views/orders/index.html.erb, test/application_system_test_case.rb, test/system/grade_books_test.rb, test/system/user_manages_classrooms_test.rb, test/system/user_manages_orders_test.rb, test/system/user_manages_schools_test.rb
fixes #590 
add system tests to GH actions
=> Fix systems tests and add them to GH actions

app/dashboards/teacher_dashboard.rb, db/migrate/20250915224900_add_name_to_users.rb, db/schema.rb, db/seeds/partials/users.rb, test/controllers/admin/teachers_controller_test.rb
it resolves https://github.com/rubyforgood/stocks-in-the-future/issues/393
- Add name to teacher
- CRUD on dashboard
- Update seed data
- Add basic test cases
=> 393 add name to teachers

app/policies/application_policy.rb, test/policies/application_policy_test.rb
no functional change, only refactoring and test coverage a bit
=> Improve application policy

app/assets/stylesheets/application.css, config/routes.rb, test/controllers/admin/school_years_controller_test.rb
Add the ability to create/edit a school year for admin #625
=> Add school years resource and tests

db/seeds/partials/stocks.rb
Resolves #662 
Added Archived Stocks:
SIRI - SiriusXM
DIS - Disney
EA - Electronic Arts
UA - Under Armour
TWX - Time Warner
META - Facebook
LUV - Southwest Airlines
GPS - Gap
=> Add archived stocks

db/migrate/20251001164806_create_solid_queue.rb, db/schema.rb
Remove queue_schema.rb
Put the schema in a migration file
=> Solid Queue to use migration

app/views/classrooms/_classroom_students_table.html.erb
No ticket - just updating the icon for reset password per our designer
=> Update password reset icon
