rubyforgood/stocks-in-the-future

bin/docker-entrypoint
Quotes around the comparison string mean that the `*` is not globbed
=> Fix the entrypoint to actually run migrations

.github/workflows/build.yml, .github/workflows/docker-build.yml, .github/workflows/lint.yml, .github/workflows/security.yml, Gemfile, Gemfile.lock
This PR is a small part of #10.  It adds rubocop and rubocop-rspec for linting. 
See here for a test run: https://github.com/rubyforgood/stocks-in-the-future/actions/runs/5703792402/job/15456771850
@cflipse does not want this enforced so it lives in a separate workfow. 
<!-- Go through this checklist before opening your PR
X I have performed a self-review of my own code
X I have commented my code, particularly in hard-to-understand areas
X I have made corresponding changes to the documentation
X  I have added tests that prove my fix is effective or that my feature works
X New and existing unit tests pass locally with my changes
X  have run [`standardrb`](https://github.com/testdouble/standard) and verified there are no lint offenses in my code (use `standardrb --fix` to autocorrect …
=> Add security audit dependencies & fixes

README.md
Adds the db:setup command to the readme for people new to the project.
=> Add rails db:setup step to readme

.github/dependabot.yml
To enable Dependabot, this yml file must first exist. This file is not yet configured. @jasonodoom has interest in setting this up properly.
=> Add necessary file to enable dependabot in Settings

.env, README.md, config/database.yml, docker-compose.yml
Resolves #000 
Make some quality-of-life changes to the `docker-compose` file to allow the docker compose stack to peacefully co-exist with other running docker applications.
* New feature (non-breaking change which adds functionality)
* This change requires a documentation update
* Documentation update
=> Better docker ports

Gemfile, Gemfile.lock, app/controllers/admin/application_controller.rb, app/controllers/admin/classrooms_controller.rb, app/controllers/admin/portfolio_stocks_controller.rb, app/controllers/admin/portfolio_transactions_controller.rb, app/controllers/admin/portfolios_controller.rb, app/controllers/admin/school_years_controller.rb, app/controllers/admin/schools_controller.rb, app/controllers/admin/stocks_controller.rb, app/controllers/admin/students_controller.rb, app/controllers/admin/teachers_controller.rb, app/controllers/admin/users_controller.rb, app/controllers/admin/years_controller.rb, app/dashboards/classroom_dashboard.rb, app/dashboards/portfolio_dashboard.rb, app/dashboards/portfolio_stock_dashboard.rb, app/dashboards/portfolio_transaction_dashboard.rb, app/dashboards/school_dashboard.rb, app/dashboards/school_year_dashboard.rb, app/dashboards/stock_dashboard.rb, app/dashboards/student_dashboard.rb, app/dashboards/teacher_dashboard.rb, app/dashboards/user_dashboard.rb, app/dashboards/year_dashboard.rb, app/models/admin.rb, config/routes.rb
This pull request introduces the `Administrate` gem to the application and creates a set of administrative interfaces for various models. The changes primarily include the addition of the `Administrate` gem to the `Gemfile`, the creation of new controllers under the `Admin` module, and the creation of dashboard configuration files for the models.
=> Add basic administrate admin ui

app/jobs/stock_prices_update_job.rb, test/data/global_quote_ibm.json, test/data/global_quote_shz.json, test/jobs/stock_prices_update_job_test.rb
This is just the beginnings of addressing issue #146, including:
the demo data from https://www.alphavantage.co/documentation/ as it will come back from 
https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol={symbol}&apikey={api_key}
The scaffolding for a job that would call this endpoint for each symbol in a json or cvs file where we'll store the small group of stock symbols we need to update.
=> #146 Api demo data

Dockerfile.dev, README.md, bin/dc, docker-compose.yml
A proposed docker-compose.yml file for running and developing the app in docker and some supporting documentation and simple tooling to use it. 
In `Dockerfile.dev`, use `npm install -g yarn` to get yarn instead of Yarn's `corepack` recommendation. This lets us not have to reinstall corepack and yarn every time we run a command like `docker compose run stocks rails test`.
```dockerfile
RUN apt-get update -qq && \
apt-get install --no-install-recommends -y \
build-essential libpq-dev curl \
nodejs npm
RUN npm install -g yarn
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY package.json yarn.lock ./
RUN yarn
```
It might be possible to reuse the `stocks` service image to build assets, but `node:lts-alpine` has yarn preinstalled, so there's very little fiddling required to make the …
=> Basic developer tooling for running the app in Docker

.github/workflows/ci.yml, .standard.yml, Gemfile, Gemfile.lock, docker-compose.yml
This PR introduces a workflow for running the Rails test suite and [Ruby Standard](https://github.com/standardrb/standard) linter on pull requests for the project.
This workflow _works_ as currently written, but fails checks because we have test failures and linter violations.
Once those issues are fixed, we can add it as a branch protection in the project settings.
=> Ruby test and lint github action workflow

app/controllers/students_controller.rb, app/views/students/show.html.erb, config/routes.rb, test/controllers/students_controller_test.rb
Addresses issue https://github.com/rubyforgood/stocks-in-the-future/issues/144
- Displays student cash balance in student show view
=> Add students controller, test and view to display student cash balance

.github/workflows/ci.yml
We don't need this yet, and there are a lot of folks whose work would be negatively impacted if they had to merge a bunch of conflicts. 
We can pick it back up after the event. 🙌🏻
=> Ignore the Ruby Lint job in CI for now

.gitignore, Gemfile, Gemfile.lock, config/initializers/api_keys.rb, test/jobs/stock_prices_update_job_test.rb, test/test_helper.rb
This PR introduces WebMock and adds three tests for the StockPricesUpdateJob:
1. Is the API called?
2. Are records created? (skipped)
3. Are records populated? (skipped)
=> Add test stubs for stocks API

Gemfile, Gemfile.lock, app/jobs/stock_purchase_job.rb, app/policies/application_policy.rb, app/policies/order_policy.rb
- Needs to be integrated into a (currently not existing) controller with the line `authorize @order` to be useful
For issue: https://github.com/rubyforgood/stocks-in-the-future/issues/163
=> Basic pundit setup with OrderPolicy on create

.gitignore, app/jobs/stock_prices_update_job.rb, bin/dc.cmd, test/data/global_quote_dis.json, test/data/global_quote_ea.json, test/data/global_quote_f.json, test/data/global_quote_fb.json, test/data/global_quote_gps.json, test/data/global_quote_ko.json, test/data/global_quote_luv.json, test/data/global_quote_siri.json, test/data/global_quote_sne.json, test/data/global_quote_twx.json, test/data/global_quote_ua.json, test/data/stocks_roster.json, test/jobs/stock_prices_update_job_test.rb
Implements stock price update including pulling data with API thru storing in database. Includes tests and test/sample API pulled stock data. Supports #146
=> Implement stock price update job and test. Supports #146

app/controllers/admin/application_controller.rb, app/views/layouts/application.html.erb, db/migrate/20250418002328_add_admin_to_users.rb, db/schema.rb, test/controllers/admin/application_controller_test.rb, test/controllers/admin/students_controller_test.rb, test/fixtures/users.yml
Added an `admin` column to Users table and used that to add a check for admin flag in order for a user to access admin pages.
=> Add admin column to user and check for admin for access to admin pages

app/dashboards/stock_dashboard.rb, app/views/portfolios/_stock_card.html.erb, test/controllers/admin/stocks_controller_test.rb
Resolves #197
The `price_info` column was renamed to `price` in #156.
=> Change all references to stock price_info to price

app/views/devise/sessions/new.html.erb
Remove redundant links
Link to the issue:
https://github.com/rubyforgood/stocks-in-the-future/issues/209
=> Remove Devise links from the "Sign In" page

Gemfile, Gemfile.lock, app/models/classroom.rb, app/models/portfolio.rb, app/models/user.rb, app/models/year.rb, db/migrate/20250427103023_add_not_null_constraint_to_year_on_years.rb, db/schema.rb, test/factories.rb, test/fixtures/classrooms.yml, test/fixtures/school_years.yml, test/fixtures/years.yml, test/models/year_test.rb, test/test_helper.rb
This PR:
- adds tests for the year model.
- makes the year column not nullable on the database level.
- uses realistic data for year fixture.
- adds the factory_bot_rails gem for factories.
Fixtures are a great way to keep test setup simple and focused. They work especially well for establishing common baseline data that many tests can rely on.
However, fixtures shouldn't be used for every possible data permutation. Trying to model every variation with fixtures tends to make them bloated, hard to understand, and brittle. Similarly, mutating existing fixtures inside a test to fit a specific need is generally considered an anti-pattern that undermines the clarity and reliability that fixtures are supposed to provide.
Because of these trade-offs, I recommend a hybrid approach:
- Use fixtures …
=> Test Year Model

app/controllers/classrooms_controller.rb, app/dashboards/year_dashboard.rb, app/models/year.rb, app/views/classrooms/_classroom.html.erb, db/migrate/20250526201022_change_year_column_to_name_and_update_type.rb, db/schema.rb, db/seeds.rb, test/factories/years.rb, test/models/year_test.rb
- Replaced the `year` attribute with `name` across the `Year` model.
- Updated validations, migrations, related controllers, views, tests, and seeds to reflect the updated naming and data type.
Fixing #244
=> Update `Year` model to replace `year` attribute with `name`

app/views/classrooms/_classroom.html.erb
Fix #252 
- Added delete link to the classroom index page
=> Add delete link to classrooms list with turbo method

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/custom/buttons.css, app/assets/stylesheets/custom/forms.css, app/views/classrooms/_classroom.html.erb, app/views/classrooms/_classroom_students_table.html.erb, app/views/classrooms/_form.html.erb, app/views/classrooms/edit.html.erb, app/views/classrooms/index.html.erb, app/views/classrooms/new.html.erb, app/views/classrooms/show.html.erb, app/views/schools/_school.html.erb, app/views/schools/edit.html.erb, app/views/schools/show.html.erb, app/views/stocks/_stock.html.erb, app/views/stocks/_stocks_table.html.erb, app/views/stocks/show.html.erb
We want to encourage tailwind utility class changes to be streamlined -- in one place. That way, it just cascades to all the view elements automatically.
- More button work
- Css file to consolidate form element style classes
We do that here for buttons -- they are centralized as css classes in `app/assets/stylesheets/custom/buttons.css`. I did not swap out all partials with direct tw utility class markups. That will come later, when those flows are worked on.
The focus here is consolidation. We expect change, eg `tw-btn-buy` and `tw-btn-sell` were simply created to accommodate the likelihood that they are different from the rest.
Same idea with form elements.
=> [Issue-332] more consolidation of buttons styles; also forms.css for input element styles

app/dashboards/school_dashboard.rb, app/dashboards/year_dashboard.rb
Fixes #288
- Removed the school_year select field from the new and edit forms in the School dashboard.
- Updated the admin interface to display the year name instead of the default '`Year #1`' format for Year records.
=> Fix year select in school edit 288

app/views/orders/_form.html.erb
I have updated the "Total Earnings" text when selling the stock. Made sure to show "Total Costs" when buying stocks aswell.
Selling Stock:
Buying Stock:
close #402
=> feat(orders): display earnings for sell orders

app/dashboards/stock_dashboard.rb, app/models/stock.rb, db/migrate/20250903103019_add_archived_to_stocks.rb, db/schema.rb, test/models/stock_test.rb
It resolves https://github.com/rubyforgood/stocks-in-the-future/issues/430
- Adding archived attribute 
- Show the new attributes on the admin page
- Admin can see and edit the new attribute
- Active and archived scopes
I added the attribute and remove the `cash_flow` to keep information minimal and useful
=> #430 stock can be archived

app/views/classrooms/_classroom_students_table.html.erb, app/views/classrooms/show.html.erb
-  Replace Edit/Delete text links with FontAwesome icons (`fa-pencil`, `fa-trash`, `fa-key`)
-  Add hover effects and color-coded actions for better UX
-  Improve button styling and table spacing
-  Better organize `classroom` action buttons
Resolves #499
=> Fix classroom show page: replace text links with FA icons

app/assets/stylesheets/custom/buttons.css, app/controllers/classrooms_controller.rb, app/dashboards/classroom_dashboard.rb, app/views/classrooms/_form.html.erb, app/views/classrooms/index.html.erb
Display teacher in classroom table and make it selectable in the edit form (see #508).
- Add teacher selection with checkboxes in classroom form
- Display assigned teachers as badges in classroom index table
- Eager load teacher associations to prevent N+1 queries
- Update admin dashboard to include teachers column
- Handle empty teacher assignments gracefully
---
Closes #508
=> Add teacher name display and assignment to classrooms

app/dashboards/student_dashboard.rb, app/dashboards/teacher_dashboard.rb
Fixes #465 
Wherever a `Student` or `Teacher` resource is displayed, their username will be displayed instead of their id. This implements the request in the issue to change how these resources are displayed in select elements, and also in a few other logical places like the title of an edit form. I think this implementation makes sense, but if we only want the change to apply to the selects on this classroom edit page I can change the approach.
<details>
<summary>Before changes</summary>
</details>
<details>
<summary>After changes</summary>
</details>
=> 465 Change display for `Student` and `Teacher` resources.

app/views/orders/index.html.erb
- Removed the "New Order" button from the Orders page
- Verified tests pass after removal.
- The "New Order" button is no longer needed since new orders should be made by buying/selling stock
- Removing it improves clarity for users and prevents confusion.
1. Pull this branch.
2. Run the app locally (`bin/dev` or `docker compose up`).
3. Navigate to (http://localhost:3000/orders)
4. Confirm that the "New Order" button is no longer visible in the top right
5. Run test suite (`bin/rails test`) to confirm no issues.
- No database changes required.
- All existing tests pass.
=> removed New Order button from the Orders/Transactions page

app/controllers/classrooms_controller.rb, app/controllers/students_controller.rb, app/models/classroom.rb, config/locales/en.yml, test/controllers/students_controller_test.rb, test/models/classroom_test.rb
After implementing soft delete, three issues remained:
1. Discarded students still showed on classroom pages
2. Clicking "Delete" on already-deleted students crashed the app
3. Classroom stats counted discarded students
- `StudentsController#set_student` uses `.kept.find()` with error handling
- `ClassroomsController#show` and stats use `.kept` scope  
- `Classroom#students` association scoped to exclude discarded records
- Added `students.not_found` translation key
- Added unit and integration tests for discarded student scenarios
```ruby
test "students association excludes discarded students"
test "teacher is redirected when accessing discarded student"
```
- Discarded students disappear from classroom pages immediately
- No more crashes when trying to delete already-deleted students
- …
=> Fix soft delete issues with discarded students

.github/workflows/lint.yml, bin/lint, config/locales/en.yml
This PR fixes the `bin/lint` script and uses it as part of our CI workflow. `bundle exec i18n-tasks normalize` was also ran to normalize our locales.
=> Run All Linters In CI

README.md
The RuboCop badge stopped working because the associated file in .github/workflows was renamed.  This pull request updates the README.md file to reflect the new filename.  You can see what the repository would look like with this correction at https://github.com/jhsu802701/stocks-in-the-future/tree/fix-lint-badge .
=> Updated the Lint status badge

app/models/school_year.rb, test/models/school_year_test.rb
It resolves https://github.com/rubyforgood/stocks-in-the-future/issues/624
prevent removalof the  school year with associations
=> 624 school year cannot be deleted if it has associations

app/models/quarter.rb, app/models/year.rb, test/models/quarter_test.rb, test/models/year_test.rb
The current `previous` and `next` methods **only work within the same school year**. They look for quarters with `number - 1` or `number + 1` within the same `school_year`.
**What happens now:**
- If you're in Q1 and call `previous`, it looks for Q0 (doesn't exist) → returns `nil`
- If you're in Q4 and call `next`, it looks for Q5 (doesn't exist) → returns `nil`
**What we need:**
- Q1 2022-2023 `previous` should return Q4 2021-2022
- Q4 2021-2022 `next` should return Q1 2022-2023
**The core issue:** There's no mechanism to navigate across different school years, even though quarters naturally flow from one school year to the next in a continuous sequence.
- Im lukewarm about using keywords like `next`. So I prefer `next_thing`. OTOH I also understand the value of consistency. I know …
=> Issue-660: smarter quarters to allow next and previous navigation across years

app/assets/tailwind/admin.css, app/views/admin/students/_form.html.erb
Why?
The dropdown element is not visible on the student edit page. 
What?
Since most of the page looks like it's rendered by the administrate gem, I went ahead and just added some custom css to keep it in line with the other elements in its form.
Future changes:
I am not super familiar with this app yet so I just kept it simple for now, I imagine we would want to add some css for all select elements at a certain point.
=> Add tailwind css to transaction type element on the admin student edit view (resolves #688)

app/views/stocks/show.html.erb
It resolves https://github.com/rubyforgood/stocks-in-the-future/issues/605
=> 605 add logo to stock show page

app/views/portfolios/show.html.erb
Added red/green color styling to the Total Return column to match the Change column. Positive returns show in green with a + prefix, negative returns show in red.
Fixes #684
=> Add color coding to Total Return column in portfolio table

db/seeds/staging.rb
Heroku deployments to staging environment were failing when running `heroku rake db:seed` because we didn't have a staging file
Added: db/seeds/staging.rb - loads development seeds for staging environment
We want all the sample data we have for development in staging so we can play around with it
=> Add missing staging.rb seeds file so we can seed in staging
